version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/back-end"
    labels:
      - "dependabot"
      - "poetry"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/front-end"
    labels:
      - "dependabot"
      - "npm"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
