{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}
  labels:
    {{- include "aas-backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
###########################################
## Assign container anyuid system role ##
##############################################
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}-role
  namespace: ai-appstore
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - anyuid
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}-rolebinding
  namespace: ai-appstore
subjects:
  - kind: ServiceAccount
    name: {{ include "aas-backend.serviceAccountName" . }}
    namespace: ai-appstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aas-backend.serviceAccountName" . }}-role
  namespace: ai-appstore


#############################################################################
## Assign container rights for managing spawn container
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}-kpa
rules:
  # to allow manage a deployment in APIGroup "apps"
  - apiGroups:
    - "apps"
    resources:
      - deployments
      - deployments/status
      - deployments/scale
    verbs: ["create", "get", "list", "delete", "patch"] # patch, get, list, create, delete
  # to allow manage a deployment in APIGroup "", coreapi
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - services
    verbs: ["create", "get", "list", "delete", "patch"] # patch, get, list, create, delete
  # to allow manage a mappings in cusrtom APIGroup "getambassador.io"
  - apiGroups:
    - "getambassador.io"
    resources:
      - mappings
    verbs: ["create", "delete", "patch"] # patch, create, delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}-kpa-role-binding
  namespace: ai-appstore
subjects:
  - kind: ServiceAccount
    name: {{ include "aas-backend.serviceAccountName" . }}
    namespace: ai-appstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aas-backend.serviceAccountName" . }}-kpa
  namespace: ai-appstore
{{- end }}