{{- if .Values.serviceAccountengines.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}-engines
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aas-backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}-engines-role
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - anyuid
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}-engines-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aas-backend.serviceAccountName" . }}-engines
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aas-backend.serviceAccountName" . }}-engines-role
  namespace: {{ .Release.Namespace }}
{{- end }}