name: Publish Documentation to GitHub Pages

on:
  push: # run only on push to avoid updating documentation til everything is checked out
    branches:
      - main
    paths: # only following two are required as api documentation is under backend and pages documentation is udner docs as part of sphinx workflow
      - 'back-end/**'
      - 'docs/**'
  workflow_dispatch: # Allow manual invokation of run

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.2
      - run: |
          poetry install
      - name: Build documentation
        run: |
          poetry run sphinx-build -M html "source" "build"
      - name: Upload page as artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/build/html'
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v1
